#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────
# build-bundle.sh  –  Concatenate common CSS files into bundle.css
#
# This script merges all design-system + common component CSS files
# into a single bundle.css to reduce HTTP requests.
#
# Page-specific CSS files (cart.css, wallet.css, etc.) are NOT included —
# they are still loaded individually via the extra_css mechanism in head.html.
#
# Usage:  ./build-bundle.sh          (run from this directory)
#         bash frontend/platform/static/css/build-bundle.sh  (from repo root)
# ─────────────────────────────────────────────────────────────

set -euo pipefail

# Resolve the CSS directory (where this script lives)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUNDLE="$SCRIPT_DIR/bundle.css"

echo "🔧 Building CSS bundle..."

# Order matters: tokens first, then design system, then common styles
FILES=(
    # 0. Fonts (must be first so @font-face is available)
    "fonts.css"

    # 1. Design System Tokens (defines CSS custom properties)
    "dashboard-tokens.css"
    "unified-styles.css"

    # 2. Design System Components
    "ds-page-layout.css"
    "ds-buttons.css"
    "ds-badges.css"
    "ds-cards.css"
    "ds-forms.css"
    "ds-tables.css"
    "ds-typography.css"
    "ds-modals.css"
    "ds-utilities.css"
    "ds-progress.css"

    # 3. Common / Layout
    "main.css"
    "property-item-card.css"
    "sidebar-navigation.css"
    "bem/sidebar.css"
    "sidebar-developer.css"
    "community-card.css"
    "profile-dropdown.css"

    # 4. Mobile Common
    "mobile-header.css"
    "mobile-burger-menu.css"
    "mobile-profile-dropdown.css"

    # 5. Components
    "poool-dropdown.css"
)

# Start with a header comment
cat > "$BUNDLE" <<'EOF'
/*! ═══════════════════════════════════════════════════════════
 *  POOOL CSS Bundle (auto-generated — do not edit by hand)
 *  Generated by: build-bundle.sh
 *  Contains: design system tokens, DS components, and common styles
 *  ═══════════════════════════════════════════════════════════ */

EOF

# Concatenate each file with a separator comment
for file in "${FILES[@]}"; do
    filepath="$SCRIPT_DIR/$file"
    if [[ -f "$filepath" ]]; then
        echo "" >> "$BUNDLE"
        echo "/* ── ${file} ────────────────────────────────── */" >> "$BUNDLE"
        echo "" >> "$BUNDLE"
        cat "$filepath" >> "$BUNDLE"
        echo "" >> "$BUNDLE"
    else
        echo "⚠️  Warning: $file not found, skipping."
    fi
done

# Calculate stats
FILECOUNT=${#FILES[@]}
BUNDLESIZE=$(wc -c < "$BUNDLE" | tr -d ' ')
BUNDLESIZE_KB=$((BUNDLESIZE / 1024))

echo "✅ Bundle created: bundle.css"
echo "   Files merged:  $FILECOUNT"
echo "   Bundle size:   ${BUNDLESIZE_KB}KB ($BUNDLESIZE bytes)"
echo ""
echo "   Requests saved per page load: $((FILECOUNT - 1))"
