-- Repair Demo Apartment 01 seed/content drift surfaced by checkout E2E.
-- Idempotent: creates the named demo listing when absent, otherwise updates only
-- the fields that drifted in production/browser testing.

INSERT INTO assets (
    title,
    slug,
    short_description,
    description,
    asset_type,
    property_type,
    area,
    lease_type,
    lease_term_years,
    land_size_sqm,
    building_size_sqm,
    bedrooms,
    bathrooms,
    construction_status,
    year_built,
    location_city,
    location_country,
    location_address,
    location_description,
    total_value_cents,
    token_price_cents,
    tokens_total,
    tokens_available,
    annual_yield_bps,
    capital_appreciation_bps,
    occupancy_rate_bps,
    funding_status,
    featured,
    published,
    default_investment_amount_cents,
    default_rental_yield_bps,
    default_value_growth_bps,
    investment_type,
    investment_type_description,
    leasing_strategy_type,
    leasing_strategy_description,
    risk_notification,
    escrow_agent
)
VALUES (
    'Demo Apartment 01 - Investment',
    'demo-apartment-01---investment-6016e69e-15d0-4547-996a-ca560541f3fa',
    'Two-bedroom investment apartment in Uluwatu with professional property management and monthly rental income target.',
    'Apartment ULU is a two-bedroom investment apartment in Uluwatu designed for fractional ownership. The asset is positioned for investors seeking a smaller ticket size, transparent funding progress, and professionally managed rental income.

The apartment includes two bedrooms, one bathroom, an efficient kitchen and dining area, and a balcony outlook. It is offered as a freehold investment with operations handled by the POOOL property management team. Investor distributions begin after the property is fully funded and the share certificates are issued.',
    'real_estate',
    'apartment',
    'Uluwatu',
    'freehold',
    25,
    120.00,
    72.00,
    2,
    1,
    'ready',
    2024,
    'Uluwatu',
    'ID',
    'Uluwatu, Bali, Indonesia',
    'Apartment ULU is located in Uluwatu, Bali, with access to beaches, cafes, wellness venues, and the Bukit Peninsula tourism corridor. The location supports short- and mid-term rental demand while keeping the asset profile focused on a compact apartment rather than a villa.',
    1000000000,
    100000,
    10000,
    6000,
    1000,
    100,
    8500,
    'funding_in_progress',
    TRUE,
    TRUE,
    200000,
    1000,
    100,
    'rental_yield',
    'Apartment rental yield investment.',
    'professionally_managed',
    'Managed apartment rentals with POOOL property management oversight.',
    'Property investments carry liquidity, FX, occupancy, and operating risks.',
    'poool_escrow'
)
ON CONFLICT (slug) DO UPDATE
SET
    title = EXCLUDED.title,
    short_description = EXCLUDED.short_description,
    description = EXCLUDED.description,
    property_type = EXCLUDED.property_type,
    area = EXCLUDED.area,
    lease_type = EXCLUDED.lease_type,
    lease_term_years = EXCLUDED.lease_term_years,
    land_size_sqm = EXCLUDED.land_size_sqm,
    building_size_sqm = EXCLUDED.building_size_sqm,
    bedrooms = EXCLUDED.bedrooms,
    bathrooms = EXCLUDED.bathrooms,
    construction_status = EXCLUDED.construction_status,
    year_built = EXCLUDED.year_built,
    location_city = EXCLUDED.location_city,
    location_country = EXCLUDED.location_country,
    location_address = EXCLUDED.location_address,
    location_description = EXCLUDED.location_description,
    annual_yield_bps = EXCLUDED.annual_yield_bps,
    capital_appreciation_bps = EXCLUDED.capital_appreciation_bps,
    occupancy_rate_bps = EXCLUDED.occupancy_rate_bps,
    funding_status = EXCLUDED.funding_status,
    featured = EXCLUDED.featured,
    published = EXCLUDED.published,
    default_investment_amount_cents = EXCLUDED.default_investment_amount_cents,
    default_rental_yield_bps = EXCLUDED.default_rental_yield_bps,
    default_value_growth_bps = EXCLUDED.default_value_growth_bps,
    investment_type = EXCLUDED.investment_type,
    investment_type_description = EXCLUDED.investment_type_description,
    leasing_strategy_type = EXCLUDED.leasing_strategy_type,
    leasing_strategy_description = EXCLUDED.leasing_strategy_description,
    risk_notification = EXCLUDED.risk_notification,
    escrow_agent = EXCLUDED.escrow_agent,
    updated_at = NOW();
