//! Phase-5: payout connector dispatch.
//!
//! Reads the affiliate's default `affiliate_payout_methods` row and
//! dispatches the actual transfer to the right downstream connector.
//! The SEPA path remains internal (covered by `service::generate_sepa_pain001_for_batch`
//! producing an XML the operator uploads to their bank); PayPal / Wise /
//! Stripe Connect / USDC are external API calls.
//!
//! THIS MODULE IS A SCAFFOLD. Each non-SEPA branch logs the intended
//! call + returns a `Mocked` reference so the admin payout-batch flow
//! is exercise-able end-to-end. Wiring the real API client (auth + body
//! shape per provider) is intentionally deferred to a follow-up task —
//! the dispatch surface here is stable so the admin batch handler can
//! adopt it now.
//!
//! How to use:
//! ```ignore
//! let res = payout_connectors::dispatch_payout(&pool, PayoutDispatch {
//!     affiliate_id, amount_cents: 12_345, currency: "EUR".into(),
//!     reference: "batch:abc".into(),
//! }).await?;
//! // res.method_type tells you which connector handled it,
//! // res.provider_reference is the bank/PayPal/Wise/etc tx id.
//! ```

use crate::error::AppError;
use serde::Serialize;
use sqlx::PgPool;
use uuid::Uuid;

#[derive(Debug, Clone)]
pub struct PayoutDispatch {
    pub affiliate_id: Uuid,
    pub amount_cents: i64,
    pub currency: String,
    /// Free-form operator reference shown on the bank statement / PayPal
    /// note. Usually `"poool-batch-{batch_id_short}"`.
    pub reference: String,
}

#[derive(Debug, Serialize)]
pub struct DispatchResult {
    pub method_type: String,
    /// Provider-side reference (Wise transfer id, PayPal payout-batch-id, …).
    /// Empty string for SEPA (operator-driven) until they file the XML.
    pub provider_reference: String,
    pub status: DispatchStatus,
    pub message: String,
}

#[derive(Debug, Serialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum DispatchStatus {
    /// Connector accepted the transfer; provider_reference set.
    Accepted,
    /// SEPA-only: operator will file the XML batch manually.
    PendingOperator,
    /// Connector failed (network, auth, validation, etc.).
    Failed,
    /// Connector is a scaffold — call site recognises this and falls back
    /// to internal SEPA / operator escalation.
    Mocked,
}

/// Look up the default active payout method for `affiliate_id` and call
/// the matching connector. Returns `Failed` with a descriptive message
/// if no default method is configured (caller decides whether to fall
/// back to the legacy `developer_teams.bank_iban_*` path).
pub async fn dispatch_payout(
    pool: &PgPool,
    input: PayoutDispatch,
) -> Result<DispatchResult, AppError> {
    let method = sqlx::query!(
        r#"SELECT id, method_type, identifier_encrypted, identifier_plain
             FROM affiliate_payout_methods
            WHERE affiliate_id = $1 AND is_default = TRUE AND is_active = TRUE
            LIMIT 1"#,
        input.affiliate_id
    )
    .fetch_optional(pool)
    .await?;

    let Some(m) = method else {
        return Ok(DispatchResult {
            method_type: "none".into(),
            provider_reference: String::new(),
            status: DispatchStatus::Failed,
            message: "No default payout method configured. Falling back to legacy SEPA path."
                .into(),
        });
    };

    match m.method_type.as_str() {
        "sepa_iban" => dispatch_sepa(input).await,
        "paypal_email" => {
            let dest = m.identifier_plain.unwrap_or_default();
            dispatch_paypal(input, &dest).await
        }
        "wise_email" => {
            let dest = m.identifier_plain.unwrap_or_default();
            dispatch_wise(input, &dest).await
        }
        "usdc_wallet" => {
            let dest = m.identifier_plain.unwrap_or_default();
            dispatch_usdc(input, &dest).await
        }
        "stripe_connect" => {
            let dest = m.identifier_plain.unwrap_or_default();
            dispatch_stripe(input, &dest).await
        }
        other => Ok(DispatchResult {
            method_type: other.into(),
            provider_reference: String::new(),
            status: DispatchStatus::Failed,
            message: format!("Unknown method_type {}", other),
        }),
    }
}

async fn dispatch_sepa(input: PayoutDispatch) -> Result<DispatchResult, AppError> {
    // SEPA is operator-driven: the batch XML is generated by
    // `service::generate_sepa_pain001_for_batch` and uploaded to the
    // bank portal. The dispatch result here just acknowledges that
    // the operator will pick it up. The actual money movement
    // happens hours later.
    tracing::info!(
        affiliate_id = %input.affiliate_id,
        amount_cents = input.amount_cents,
        currency = %input.currency,
        ref = %input.reference,
        "SEPA payout queued for operator (pain.001 export)"
    );
    Ok(DispatchResult {
        method_type: "sepa_iban".into(),
        provider_reference: String::new(),
        status: DispatchStatus::PendingOperator,
        message: "Queued for SEPA pain.001 batch export.".into(),
    })
}

async fn dispatch_paypal(
    input: PayoutDispatch,
    destination_email: &str,
) -> Result<DispatchResult, AppError> {
    // Phase-6: real PayPal Payouts API integration.
    //
    // Two-step:
    //   1. OAuth: POST /v1/oauth2/token (grant_type=client_credentials,
    //      Basic auth client_id:secret) → access_token
    //   2. Payout: POST /v1/payments/payouts with the access_token
    //
    // Env:
    //   PAYPAL_CLIENT_ID, PAYPAL_CLIENT_SECRET — required
    //   PAYPAL_API_BASE                       — defaults to sandbox
    //                                             (https://api-m.sandbox.paypal.com)
    //                                             Set to https://api-m.paypal.com
    //                                             for prod.
    //
    // When the env vars are missing we fall back to `Mocked` so dev /
    // CI environments don't blow up on real money calls.
    let client_id = match std::env::var("PAYPAL_CLIENT_ID") {
        Ok(v) if !v.trim().is_empty() => v,
        _ => return paypal_mocked(input, destination_email, "PAYPAL_CLIENT_ID not set"),
    };
    let client_secret = match std::env::var("PAYPAL_CLIENT_SECRET") {
        Ok(v) if !v.trim().is_empty() => v,
        _ => return paypal_mocked(input, destination_email, "PAYPAL_CLIENT_SECRET not set"),
    };
    let api_base = std::env::var("PAYPAL_API_BASE")
        .unwrap_or_else(|_| "https://api-m.sandbox.paypal.com".into());

    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(20))
        .build()
        .map_err(|e| AppError::Internal(format!("paypal http client: {}", e)))?;

    // 1. OAuth
    let token_res = client
        .post(format!("{}/v1/oauth2/token", api_base))
        .basic_auth(&client_id, Some(&client_secret))
        .form(&[("grant_type", "client_credentials")])
        .send()
        .await;
    let access_token = match token_res {
        Ok(r) if r.status().is_success() => {
            let v: serde_json::Value = r.json().await.unwrap_or_default();
            v.get("access_token")
                .and_then(|t| t.as_str())
                .map(|s| s.to_string())
                .unwrap_or_default()
        }
        Ok(r) => {
            let status = r.status();
            let body = r.text().await.unwrap_or_default();
            tracing::error!("PayPal OAuth failed: {} — {}", status, body);
            return Ok(DispatchResult {
                method_type: "paypal_email".into(),
                provider_reference: String::new(),
                status: DispatchStatus::Failed,
                message: format!("PayPal OAuth failed: HTTP {}", status),
            });
        }
        Err(e) => {
            return Ok(DispatchResult {
                method_type: "paypal_email".into(),
                provider_reference: String::new(),
                status: DispatchStatus::Failed,
                message: format!("PayPal OAuth network error: {}", e),
            });
        }
    };
    if access_token.is_empty() {
        return Ok(DispatchResult {
            method_type: "paypal_email".into(),
            provider_reference: String::new(),
            status: DispatchStatus::Failed,
            message: "PayPal OAuth response missing access_token".into(),
        });
    }

    // 2. Payout. PayPal expects whole + cents in the "value" string,
    //    formatted to 2dp. The currency code goes alongside.
    let amount_str = format!(
        "{}.{:02}",
        input.amount_cents / 100,
        input.amount_cents.abs() % 100
    );
    let sender_batch_id = format!("poool-aff-{}", input.reference);
    let body = serde_json::json!({
        "sender_batch_header": {
            "sender_batch_id": sender_batch_id,
            "email_subject": "Your POOOL affiliate payout",
            "email_message": format!("Affiliate payout from POOOL: {} {}",
                amount_str, input.currency),
        },
        "items": [{
            "recipient_type": "EMAIL",
            "receiver": destination_email,
            "amount": { "value": amount_str, "currency": input.currency },
            "sender_item_id": input.reference,
            "note": format!("POOOL affiliate commission payout — ref {}", input.reference),
        }]
    });

    let payout_res = client
        .post(format!("{}/v1/payments/payouts", api_base))
        .bearer_auth(&access_token)
        .json(&body)
        .send()
        .await;
    match payout_res {
        Ok(r) if r.status().is_success() || r.status().as_u16() == 201 => {
            let v: serde_json::Value = r.json().await.unwrap_or_default();
            let batch_id = v
                .pointer("/batch_header/payout_batch_id")
                .and_then(|s| s.as_str())
                .unwrap_or("")
                .to_string();
            tracing::info!(
                affiliate_id = %input.affiliate_id,
                payout_batch_id = %batch_id,
                amount_cents = input.amount_cents,
                "[FINANCIAL] PayPal payout submitted"
            );
            Ok(DispatchResult {
                method_type: "paypal_email".into(),
                provider_reference: batch_id,
                status: DispatchStatus::Accepted,
                message: "PayPal payout accepted; final settlement is async.".into(),
            })
        }
        Ok(r) => {
            let status = r.status();
            let body_txt = r.text().await.unwrap_or_default();
            tracing::error!("PayPal payout failed: {} — {}", status, body_txt);
            Ok(DispatchResult {
                method_type: "paypal_email".into(),
                provider_reference: String::new(),
                status: DispatchStatus::Failed,
                message: format!("PayPal payout failed: HTTP {}", status),
            })
        }
        Err(e) => Ok(DispatchResult {
            method_type: "paypal_email".into(),
            provider_reference: String::new(),
            status: DispatchStatus::Failed,
            message: format!("PayPal network error: {}", e),
        }),
    }
}

fn paypal_mocked(
    input: PayoutDispatch,
    dest: &str,
    reason: &str,
) -> Result<DispatchResult, AppError> {
    tracing::warn!(
        affiliate_id = %input.affiliate_id,
        amount_cents = input.amount_cents,
        destination_email = dest,
        reason = reason,
        "[MOCK] PayPal payout — env var missing, returning Mocked status"
    );
    Ok(DispatchResult {
        method_type: "paypal_email".into(),
        provider_reference: format!("MOCK-PP-{}", input.reference),
        status: DispatchStatus::Mocked,
        message: format!("PayPal connector mocked ({}).", reason),
    })
}

async fn dispatch_wise(
    input: PayoutDispatch,
    destination_email: &str,
) -> Result<DispatchResult, AppError> {
    // Phase-6: real Wise (TransferWise) Transfers API integration.
    //
    // Multi-step:
    //   1. POST /v1/accounts                 → create recipient by email
    //   2. POST /v3/profiles/{p}/quotes      → quote source → target amount
    //   3. POST /v1/transfers                → create transfer
    //   4. POST /v3/profiles/{p}/transfers/{t}/payments → fund via balance
    //
    // Env:
    //   WISE_API_TOKEN   — required (Bearer)
    //   WISE_PROFILE_ID  — required (the platform's business profile)
    //   WISE_API_BASE    — defaults to sandbox
    //                      (https://api.sandbox.transferwise.tech)
    //                      Set to https://api.transferwise.com for prod.
    let token = match std::env::var("WISE_API_TOKEN") {
        Ok(v) if !v.trim().is_empty() => v,
        _ => return wise_mocked(input, destination_email, "WISE_API_TOKEN not set"),
    };
    let profile_id: i64 = match std::env::var("WISE_PROFILE_ID")
        .ok()
        .and_then(|s| s.parse().ok())
    {
        Some(v) => v,
        None => return wise_mocked(input, destination_email, "WISE_PROFILE_ID not set"),
    };
    let api_base = std::env::var("WISE_API_BASE")
        .unwrap_or_else(|_| "https://api.sandbox.transferwise.tech".into());

    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(30))
        .build()
        .map_err(|e| AppError::Internal(format!("wise http client: {}", e)))?;

    // Convert cents → decimal string (Wise wants major units).
    let target_amount: f64 = (input.amount_cents as f64) / 100.0;

    // 1. Recipient. We use the email-based recipient type Wise calls
    //    "EMAIL" — Wise emails the recipient to claim funds. Simpler
    //    than full bank-detail collection; Wise handles KYC + payout.
    let recipient_body = serde_json::json!({
        "profile": profile_id,
        "accountHolderName": destination_email,
        "currency": input.currency,
        "type": "EMAIL",
        "details": { "email": destination_email }
    });
    let recipient_id: i64 = match client
        .post(format!("{}/v1/accounts", api_base))
        .bearer_auth(&token)
        .json(&recipient_body)
        .send()
        .await
    {
        Ok(r) if r.status().is_success() => {
            let v: serde_json::Value = r.json().await.unwrap_or_default();
            v.get("id").and_then(|i| i.as_i64()).unwrap_or(0)
        }
        Ok(r) => {
            let status = r.status();
            let txt = r.text().await.unwrap_or_default();
            tracing::error!("Wise recipient-create failed: {} — {}", status, txt);
            return Ok(wise_fail(format!("Wise recipient-create: HTTP {}", status)));
        }
        Err(e) => return Ok(wise_fail(format!("Wise recipient network: {}", e))),
    };
    if recipient_id == 0 {
        return Ok(wise_fail("Wise recipient-create returned no id".into()));
    }

    // 2. Quote. We pin target-amount (the affiliate receives a known
    //    sum); Wise computes the source debit + fee.
    let quote_body = serde_json::json!({
        "sourceCurrency": "EUR",
        "targetCurrency": input.currency,
        "targetAmount": target_amount,
        "payOut": "BALANCE",
        "preferredPayIn": "BALANCE",
    });
    let quote_id: String = match client
        .post(format!("{}/v3/profiles/{}/quotes", api_base, profile_id))
        .bearer_auth(&token)
        .json(&quote_body)
        .send()
        .await
    {
        Ok(r) if r.status().is_success() => {
            let v: serde_json::Value = r.json().await.unwrap_or_default();
            v.get("id")
                .and_then(|i| i.as_str())
                .unwrap_or("")
                .to_string()
        }
        Ok(r) => {
            let status = r.status();
            let txt = r.text().await.unwrap_or_default();
            tracing::error!("Wise quote failed: {} — {}", status, txt);
            return Ok(wise_fail(format!("Wise quote: HTTP {}", status)));
        }
        Err(e) => return Ok(wise_fail(format!("Wise quote network: {}", e))),
    };
    if quote_id.is_empty() {
        return Ok(wise_fail("Wise quote returned no id".into()));
    }

    // 3. Transfer. customerTransactionId = idempotency key.
    let transfer_body = serde_json::json!({
        "targetAccount": recipient_id,
        "quoteUuid": quote_id,
        "customerTransactionId": format!("poool-aff-{}", input.reference),
        "details": {
            "reference": input.reference,
            "sourceOfFunds": "verification.source.of.funds.other",
        }
    });
    let transfer_id: i64 = match client
        .post(format!("{}/v1/transfers", api_base))
        .bearer_auth(&token)
        .json(&transfer_body)
        .send()
        .await
    {
        Ok(r) if r.status().is_success() => {
            let v: serde_json::Value = r.json().await.unwrap_or_default();
            v.get("id").and_then(|i| i.as_i64()).unwrap_or(0)
        }
        Ok(r) => {
            let status = r.status();
            let txt = r.text().await.unwrap_or_default();
            tracing::error!("Wise transfer-create failed: {} — {}", status, txt);
            return Ok(wise_fail(format!("Wise transfer-create: HTTP {}", status)));
        }
        Err(e) => return Ok(wise_fail(format!("Wise transfer network: {}", e))),
    };
    if transfer_id == 0 {
        return Ok(wise_fail("Wise transfer-create returned no id".into()));
    }

    // 4. Fund.
    let fund_res = client
        .post(format!(
            "{}/v3/profiles/{}/transfers/{}/payments",
            api_base, profile_id, transfer_id
        ))
        .bearer_auth(&token)
        .json(&serde_json::json!({ "type": "BALANCE" }))
        .send()
        .await;
    match fund_res {
        Ok(r) if r.status().is_success() => {
            tracing::info!(
                affiliate_id = %input.affiliate_id,
                wise_transfer_id = transfer_id,
                amount_cents = input.amount_cents,
                "[FINANCIAL] Wise transfer funded"
            );
            Ok(DispatchResult {
                method_type: "wise_email".into(),
                provider_reference: transfer_id.to_string(),
                status: DispatchStatus::Accepted,
                message: "Wise transfer funded; recipient claims via email.".into(),
            })
        }
        Ok(r) => {
            let status = r.status();
            let txt = r.text().await.unwrap_or_default();
            tracing::error!("Wise fund failed: {} — {}", status, txt);
            Ok(wise_fail(format!("Wise fund: HTTP {}", status)))
        }
        Err(e) => Ok(wise_fail(format!("Wise fund network: {}", e))),
    }
}

fn wise_mocked(
    input: PayoutDispatch,
    dest: &str,
    reason: &str,
) -> Result<DispatchResult, AppError> {
    tracing::warn!(
        affiliate_id = %input.affiliate_id,
        destination_email = dest,
        reason = reason,
        "[MOCK] Wise — env var missing"
    );
    Ok(DispatchResult {
        method_type: "wise_email".into(),
        provider_reference: format!("MOCK-WISE-{}", input.reference),
        status: DispatchStatus::Mocked,
        message: format!("Wise connector mocked ({}).", reason),
    })
}
fn wise_fail(message: String) -> DispatchResult {
    DispatchResult {
        method_type: "wise_email".into(),
        provider_reference: String::new(),
        status: DispatchStatus::Failed,
        message,
    }
}

async fn dispatch_usdc(
    input: PayoutDispatch,
    destination_wallet: &str,
) -> Result<DispatchResult, AppError> {
    // STUB. Real call: ERC-20 USDC `transfer(to, amount)` on the chosen
    // chain (likely Polygon or Base for sane fees), signed by the
    // platform's hot wallet held in KMS / HSM. The chain choice should
    // be configurable per-method-row (Phase 6).
    tracing::warn!(
        affiliate_id = %input.affiliate_id,
        amount_cents = input.amount_cents,
        currency = %input.currency,
        destination_wallet = destination_wallet,
        "[STUB] USDC payout connector — on-chain transfer not yet wired"
    );
    Ok(DispatchResult {
        method_type: "usdc_wallet".into(),
        provider_reference: format!("MOCK-USDC-{}", input.reference),
        status: DispatchStatus::Mocked,
        message: "USDC connector stub. Wire a KMS-signed ERC-20 transfer in payout_connectors::dispatch_usdc.".into(),
    })
}

async fn dispatch_stripe(
    input: PayoutDispatch,
    destination_account: &str,
) -> Result<DispatchResult, AppError> {
    // Phase-6: real Stripe Connect Transfer API integration.
    //
    // POST https://api.stripe.com/v1/transfers
    //   Authorization: Bearer <STRIPE_SECRET_KEY>
    //   Body (form-encoded): amount=<cents>, currency=<lower3>,
    //     destination=<acct_xxx>, transfer_group=<reference>,
    //     description=<note>
    //
    // Stripe accepts integer minor units directly (cents) so no
    // formatting needed. Currency must be lowercase per their spec.
    let secret_key = match std::env::var("STRIPE_SECRET_KEY") {
        Ok(v) if !v.trim().is_empty() => v,
        _ => return stripe_mocked(input, destination_account, "STRIPE_SECRET_KEY not set"),
    };

    if !destination_account.starts_with("acct_") {
        return Ok(DispatchResult {
            method_type: "stripe_connect".into(),
            provider_reference: String::new(),
            status: DispatchStatus::Failed,
            message: "Stripe destination must start with acct_".into(),
        });
    }

    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(20))
        .build()
        .map_err(|e| AppError::Internal(format!("stripe http client: {}", e)))?;

    // Idempotency key — Stripe deduplicates identical requests with the
    // same key for 24h. The batch reference is unique per (batch, affiliate).
    let idempotency_key = format!("poool-aff-{}", input.reference);
    let currency_lower = input.currency.to_ascii_lowercase();
    let form = [
        ("amount", input.amount_cents.to_string()),
        ("currency", currency_lower),
        ("destination", destination_account.to_string()),
        ("transfer_group", input.reference.clone()),
        (
            "description",
            format!("POOOL affiliate commission — ref {}", input.reference),
        ),
    ];

    let res = client
        .post("https://api.stripe.com/v1/transfers")
        .bearer_auth(&secret_key)
        .header("Idempotency-Key", &idempotency_key)
        .form(&form)
        .send()
        .await;
    match res {
        Ok(r) if r.status().is_success() => {
            let v: serde_json::Value = r.json().await.unwrap_or_default();
            let transfer_id = v
                .get("id")
                .and_then(|s| s.as_str())
                .unwrap_or("")
                .to_string();
            tracing::info!(
                affiliate_id = %input.affiliate_id,
                stripe_transfer_id = %transfer_id,
                amount_cents = input.amount_cents,
                "[FINANCIAL] Stripe Connect transfer submitted"
            );
            Ok(DispatchResult {
                method_type: "stripe_connect".into(),
                provider_reference: transfer_id,
                status: DispatchStatus::Accepted,
                message: "Stripe transfer created.".into(),
            })
        }
        Ok(r) => {
            let status = r.status();
            let body_txt = r.text().await.unwrap_or_default();
            tracing::error!("Stripe transfer failed: {} — {}", status, body_txt);
            Ok(DispatchResult {
                method_type: "stripe_connect".into(),
                provider_reference: String::new(),
                status: DispatchStatus::Failed,
                message: format!("Stripe transfer failed: HTTP {}", status),
            })
        }
        Err(e) => Ok(DispatchResult {
            method_type: "stripe_connect".into(),
            provider_reference: String::new(),
            status: DispatchStatus::Failed,
            message: format!("Stripe network error: {}", e),
        }),
    }
}

fn stripe_mocked(
    input: PayoutDispatch,
    dest: &str,
    reason: &str,
) -> Result<DispatchResult, AppError> {
    tracing::warn!(
        affiliate_id = %input.affiliate_id,
        destination_account = dest,
        reason = reason,
        "[MOCK] Stripe Connect — env var missing"
    );
    Ok(DispatchResult {
        method_type: "stripe_connect".into(),
        provider_reference: format!("MOCK-STRIPE-{}", input.reference),
        status: DispatchStatus::Mocked,
        message: format!("Stripe Connect mocked ({}).", reason),
    })
}
