// Page manifest for Miro UX-review screenshots.
// Routes are relative to BASE_URL. requires_auth=true means login first.
// Pages with optional query params are noted in "params" (try without first, mark skip if empty-state useless).

export const PAGES = [
  // ===== PUBLIC =====
  { id: "public-landing",                role: "public",    route: "/landing",                          requires_auth: false, bucket: "F" },
  { id: "public-landing-v2",             role: "public",    route: "/landing-v2",                       requires_auth: false, bucket: "F" },
  { id: "public-login",                  role: "public",    route: "/auth/login",                       requires_auth: false, bucket: "B" },
  { id: "public-signup",                 role: "public",    route: "/signup",                           requires_auth: false, bucket: "B" },
  { id: "public-forgot-password",        role: "public",    route: "/forgot-password",                  requires_auth: false, bucket: "B" },
  { id: "public-reset-password",         role: "public",    route: "/reset-password",                   requires_auth: false, bucket: "B" },
  { id: "public-verify-email",           role: "public",    route: "/verify-email",                     requires_auth: false, bucket: "B" },
  { id: "public-terms",                  role: "public",    route: "/terms",                            requires_auth: false, bucket: "F" },
  { id: "public-privacy-policy",         role: "public",    route: "/privacy-policy",                   requires_auth: false, bucket: "F" },
  { id: "public-cookies",                role: "public",    route: "/cookies",                          requires_auth: false, bucket: "F" },
  { id: "public-imprint",                role: "public",    route: "/imprint",                          requires_auth: false, bucket: "F" },
  { id: "public-aml-kyc-policy",         role: "public",    route: "/aml-kyc-policy",                   requires_auth: false, bucket: "F" },
  { id: "public-currency-policy",        role: "public",    route: "/currency-policy",                  requires_auth: false, bucket: "F" },
  { id: "public-gdpr-data-request",      role: "public",    route: "/gdpr-data-request",                requires_auth: false, bucket: "F" },
  { id: "public-account-deletion",       role: "public",    route: "/account-deletion",                 requires_auth: false, bucket: "F" },
  { id: "public-support",                role: "public",    route: "/support",                          requires_auth: false, bucket: "F" },
  { id: "public-affiliate-terms",        role: "public",    route: "/affiliate-terms",                  requires_auth: false, bucket: "F" },
  { id: "public-affiliate-code",         role: "public",    route: "/affiliate-code-of-conduct",        requires_auth: false, bucket: "F" },
  { id: "public-affiliate-privacy",      role: "public",    route: "/affiliate-privacy-notice",         requires_auth: false, bucket: "F" },

  // ===== INVESTOR (auth) =====
  { id: "investor-index",                role: "investor",  route: "/",                                 requires_auth: true,  bucket: "A" },
  { id: "investor-welcome",              role: "investor",  route: "/welcome",                          requires_auth: true,  bucket: "A" },
  { id: "investor-portfolio",            role: "investor",  route: "/portfolio",                        requires_auth: true,  bucket: "A" },
  { id: "investor-wallet",               role: "investor",  route: "/wallet",                           requires_auth: true,  bucket: "A" },
  { id: "investor-wallet-statement",     role: "investor",  route: "/wallet/statement",                 requires_auth: true,  bucket: "A" },
  { id: "investor-transactions",         role: "investor",  route: "/transactions",                     requires_auth: true,  bucket: "A" },
  { id: "investor-transaction-detail",   role: "investor",  route: "/transaction-detail",               requires_auth: true,  bucket: "A" },
  { id: "investor-rewards",              role: "investor",  route: "/rewards",                          requires_auth: true,  bucket: "A" },
  { id: "investor-rewards-v2",           role: "investor",  route: "/rewards-v2",                       requires_auth: true,  bucket: "A" },
  { id: "investor-marketplace",          role: "investor",  route: "/marketplace",                      requires_auth: true,  bucket: "A" },
  { id: "investor-marketplace-secondary",role: "investor",  route: "/marketplace-secondary",            requires_auth: true,  bucket: "A" },
  { id: "investor-marketplace-trading-v2",role:"investor",  route: "/marketplace-trading-v2",           requires_auth: true,  bucket: "A" },
  { id: "investor-marketplace-trading-v3",role:"investor",  route: "/marketplace-trading-v3",           requires_auth: true,  bucket: "A" },
  { id: "investor-my-trading",           role: "investor",  route: "/my-trading",                       requires_auth: true,  bucket: "A" },
  { id: "investor-cart",                 role: "investor",  route: "/cart",                             requires_auth: true,  bucket: "A" },
  { id: "investor-checkout",             role: "investor",  route: "/checkout",                         requires_auth: true,  bucket: "A" },
  { id: "investor-payment-success",      role: "investor",  route: "/payment-success",                  requires_auth: true,  bucket: "A" },
  { id: "investor-payment-in-progress",  role: "investor",  route: "/payment-in-progress",              requires_auth: true,  bucket: "A" },
  { id: "investor-trade-success",        role: "investor",  route: "/trade-success",                    requires_auth: true,  bucket: "A" },
  { id: "investor-property",             role: "investor",  route: "/property",                         requires_auth: true,  bucket: "A" },
  { id: "investor-property-public",      role: "investor",  route: "/property-public",                  requires_auth: false, bucket: "F" },
  { id: "investor-commodity",            role: "investor",  route: "/commodity",                        requires_auth: true,  bucket: "A" },
  { id: "investor-commodities-marketplace", role:"investor",route: "/commodities-marketplace",          requires_auth: true,  bucket: "A" },
  { id: "investor-commodities-preview",  role: "investor",  route: "/commodities-preview",              requires_auth: false, bucket: "F" },
  { id: "investor-leaderboard",          role: "investor",  route: "/leaderboard",                      requires_auth: true,  bucket: "A" },
  { id: "investor-community",            role: "investor",  route: "/community",                        requires_auth: true,  bucket: "A" },
  { id: "investor-community-profile",    role: "investor",  route: "/community-profile",                requires_auth: true,  bucket: "A" },
  { id: "investor-community-profile-edit",role:"investor",  route: "/community-profile-edit",           requires_auth: true,  bucket: "A" },
  { id: "investor-community-circle-settings",role:"investor",route:"/community-circle-settings",        requires_auth: true,  bucket: "A" },
  { id: "investor-community-badge",      role: "investor",  route: "/community-badge",                  requires_auth: true,  bucket: "A" },
  { id: "investor-community-hashtag",    role: "investor",  route: "/community-hashtag",                requires_auth: true,  bucket: "A" },
  { id: "investor-settings",             role: "investor",  route: "/settings",                         requires_auth: true,  bucket: "A" },
  { id: "investor-settings-notif-comm",  role: "investor",  route: "/settings-notifications-community", requires_auth: true,  bucket: "A" },
  { id: "investor-kyc",                  role: "investor",  route: "/kyc",                              requires_auth: true,  bucket: "B" },
  { id: "investor-2fa",                  role: "investor",  route: "/auth-2fa",                         requires_auth: true,  bucket: "B" },
  { id: "investor-2fa-setup",            role: "investor",  route: "/auth-2fa-setup",                   requires_auth: true,  bucket: "B" },
  { id: "investor-2fa-step-up",          role: "investor",  route: "/auth-2fa-step-up",                 requires_auth: true,  bucket: "B" },
  { id: "investor-blog-index",           role: "investor",  route: "/blog",                             requires_auth: false, bucket: "F" },

  // ===== AFFILIATE =====
  { id: "affiliate-dashboard",           role: "affiliate", route: "/affiliate-dashboard",              requires_auth: true,  bucket: "C" },
  { id: "affiliate-leaderboard",         role: "affiliate", route: "/affiliate-leaderboard",            requires_auth: true,  bucket: "C" },
  { id: "affiliate-materials",           role: "affiliate", route: "/affiliate-materials",              requires_auth: true,  bucket: "C" },
  { id: "affiliate-marketing-materials", role: "affiliate", route: "/affiliate-marketing-materials",    requires_auth: true,  bucket: "C" },
  { id: "affiliate-onboarding",          role: "affiliate", route: "/affiliate-onboarding",             requires_auth: true,  bucket: "C" },
  { id: "affiliate-promo",               role: "affiliate", route: "/affiliate-promo",                  requires_auth: true,  bucket: "C" },
  { id: "affiliate-referrals",           role: "affiliate", route: "/affiliate-referrals",              requires_auth: true,  bucket: "C" },
  { id: "affiliate-settings",            role: "affiliate", route: "/affiliate-settings",               requires_auth: true,  bucket: "C" },
  { id: "affiliate-tax",                 role: "affiliate", route: "/affiliate-tax",                    requires_auth: true,  bucket: "C" },
  { id: "affiliate-team-invite",         role: "affiliate", route: "/affiliate-team-invitation-accept", requires_auth: true,  bucket: "C" },
  { id: "affiliate-complaints",          role: "affiliate", route: "/affiliate-complaints",             requires_auth: true,  bucket: "C" },
  { id: "affiliate-qualified-payout",    role: "affiliate", route: "/affiliate-qualified-referral-payout", requires_auth: true, bucket: "C" },

  // ===== DEVELOPER =====
  { id: "developer-dashboard",           role: "developer", route: "/developer/dashboard",              requires_auth: true,  bucket: "D" },
  { id: "developer-onboarding",          role: "developer", route: "/developer/developer-onboarding",   requires_auth: true,  bucket: "D" },
  { id: "developer-application-form",    role: "developer", route: "/developer/application-form",       requires_auth: true,  bucket: "D" },
  { id: "developer-assets",              role: "developer", route: "/developer/assets",                 requires_auth: true,  bucket: "D" },
  { id: "developer-asset-detail",        role: "developer", route: "/developer/asset-detail",           requires_auth: true,  bucket: "D" },
  { id: "developer-add-asset",           role: "developer", route: "/developer/add-asset",              requires_auth: true,  bucket: "D" },
  { id: "developer-annual-data",         role: "developer", route: "/developer/annual-data",            requires_auth: true,  bucket: "D" },
  { id: "developer-doc-upload-3",        role: "developer", route: "/developer/document-upload-step3",  requires_auth: true,  bucket: "D" },
  { id: "developer-operations-dash",     role: "developer", route: "/developer/operations-dashboard",   requires_auth: true,  bucket: "D" },
  { id: "developer-operations-submit",   role: "developer", route: "/developer/operations-submit",      requires_auth: true,  bucket: "D" },
  { id: "developer-property-content",    role: "developer", route: "/developer/property-content",       requires_auth: true,  bucket: "D" },
  { id: "developer-ranking",             role: "developer", route: "/developer/ranking",                requires_auth: true,  bucket: "D" },
  { id: "developer-submissions",         role: "developer", route: "/developer/submissions",            requires_auth: true,  bucket: "D" },
  { id: "developer-submission-success",  role: "developer", route: "/developer/submission-success",     requires_auth: true,  bucket: "D" },
  { id: "developer-affiliate-team",      role: "developer", route: "/developer/affiliate-team",         requires_auth: true,  bucket: "D" },
  { id: "developer-aff-team-analytics",  role: "developer", route: "/developer/affiliate-team-analytics", requires_auth: true, bucket: "D" },
  { id: "developer-aff-team-customers",  role: "developer", route: "/developer/affiliate-team-customers", requires_auth: true, bucket: "D" },
  { id: "developer-aff-team-members",    role: "developer", route: "/developer/affiliate-team-members", requires_auth: true,  bucket: "D" },
  { id: "developer-aff-team-products",   role: "developer", route: "/developer/affiliate-team-products",requires_auth: true,  bucket: "D" },
  { id: "developer-aff-team-settings",   role: "developer", route: "/developer/affiliate-team-settings",requires_auth: true,  bucket: "D" },
  { id: "developer-aff-team-tier",       role: "developer", route: "/developer/affiliate-team-tier",    requires_auth: true,  bucket: "D" },

  // ===== ADMIN =====
  { id: "admin-index",                   role: "admin",     route: "/admin",                            requires_auth: true,  bucket: "E" },
  { id: "admin-admins",                  role: "admin",     route: "/admin/admins",                     requires_auth: true,  bucket: "E" },
  { id: "admin-users",                   role: "admin",     route: "/admin/users",                      requires_auth: true,  bucket: "E" },
  { id: "admin-user-details",            role: "admin",     route: "/admin/user-details",               requires_auth: true,  bucket: "E" },
  { id: "admin-roles",                   role: "admin",     route: "/admin/roles",                      requires_auth: true,  bucket: "E" },
  { id: "admin-approvals",               role: "admin",     route: "/admin/approvals",                  requires_auth: true,  bucket: "E" },
  { id: "admin-kyc",                     role: "admin",     route: "/admin/kyc",                        requires_auth: true,  bucket: "E" },
  { id: "admin-deposits",                role: "admin",     route: "/admin/deposits",                   requires_auth: true,  bucket: "E" },
  { id: "admin-dividends",               role: "admin",     route: "/admin/dividends",                  requires_auth: true,  bucket: "E" },
  { id: "admin-orders",                  role: "admin",     route: "/admin/orders",                     requires_auth: true,  bucket: "E" },
  { id: "admin-pending-settlements",     role: "admin",     route: "/admin/pending-settlements",        requires_auth: true,  bucket: "E" },
  { id: "admin-rewards",                 role: "admin",     route: "/admin/rewards",                    requires_auth: true,  bucket: "E" },
  { id: "admin-assets",                  role: "admin",     route: "/admin/assets",                     requires_auth: true,  bucket: "E" },
  { id: "admin-asset-details",           role: "admin",     route: "/admin/asset-details",              requires_auth: true,  bucket: "E" },
  { id: "admin-asset-tokenize",          role: "admin",     route: "/admin/asset-tokenize",             requires_auth: true,  bucket: "E" },
  { id: "admin-asset-change-requests",   role: "admin",     route: "/admin/asset-change-requests",      requires_auth: true,  bucket: "E" },
  { id: "admin-asset-change-review",     role: "admin",     route: "/admin/asset-change-review",        requires_auth: true,  bucket: "E" },
  { id: "admin-blockchain-contracts",    role: "admin",     route: "/admin/blockchain-contracts",       requires_auth: true,  bucket: "E" },
  { id: "admin-blockchain-contract-detail",role:"admin",    route: "/admin/blockchain-contract-detail", requires_auth: true,  bucket: "E" },
  { id: "admin-blockchain-sync",         role: "admin",     route: "/admin/blockchain-sync",            requires_auth: true,  bucket: "E" },
  { id: "admin-blockchain-treasury",     role: "admin",     route: "/admin/blockchain-treasury",        requires_auth: true,  bucket: "E" },
  { id: "admin-treasury",                role: "admin",     route: "/admin/treasury",                   requires_auth: true,  bucket: "E" },
  { id: "admin-compliance",              role: "admin",     route: "/admin/compliance",                 requires_auth: true,  bucket: "E" },
  { id: "admin-affiliate-applications",  role: "admin",     route: "/admin/affiliate-applications",     requires_auth: true,  bucket: "E" },
  { id: "admin-affiliate-finance",       role: "admin",     route: "/admin/affiliate-finance",          requires_auth: true,  bucket: "E" },
  { id: "admin-affiliate-fraud",         role: "admin",     route: "/admin/affiliate-fraud",            requires_auth: true,  bucket: "E" },
  { id: "admin-dev-aff-fraud",           role: "admin",     route: "/admin/admin-affiliate-fraud",      requires_auth: true,  bucket: "E" },
  { id: "admin-dev-aff-teams",           role: "admin",     route: "/admin/admin-developer-affiliate-teams", requires_auth: true, bucket: "E" },
  { id: "admin-dev-submissions",         role: "admin",     route: "/admin/developer-submissions",      requires_auth: true,  bucket: "E" },
  { id: "admin-dev-submission-review",   role: "admin",     route: "/admin/developer-submission-review",requires_auth: true,  bucket: "E" },
  { id: "admin-villa-deduction-policy",  role: "admin",     route: "/admin/villa-deduction-policy",     requires_auth: true,  bucket: "E" },
  { id: "admin-villa-history",           role: "admin",     route: "/admin/villa-history",              requires_auth: true,  bucket: "E" },
  { id: "admin-villa-operations-entry",  role: "admin",     route: "/admin/villa-operations-entry",     requires_auth: true,  bucket: "E" },
  { id: "admin-villa-operations-queue",  role: "admin",     route: "/admin/villa-operations-queue",     requires_auth: true,  bucket: "E" },
  { id: "admin-villa-valuation",         role: "admin",     route: "/admin/villa-valuation",            requires_auth: true,  bucket: "E" },
  { id: "admin-notifications",           role: "admin",     route: "/admin/notifications",              requires_auth: true,  bucket: "E" },
  { id: "admin-email-marketing",         role: "admin",     route: "/admin/email-marketing",            requires_auth: true,  bucket: "E" },
  { id: "admin-reports",                 role: "admin",     route: "/admin/reports",                    requires_auth: true,  bucket: "E" },
  { id: "admin-audit-logs",              role: "admin",     route: "/admin/audit-logs",                 requires_auth: true,  bucket: "E" },
  { id: "admin-storage",                 role: "admin",     route: "/admin/storage",                    requires_auth: true,  bucket: "E" },
  { id: "admin-system",                  role: "admin",     route: "/admin/system",                     requires_auth: true,  bucket: "E" },
  { id: "admin-settings",                role: "admin",     route: "/admin/settings",                   requires_auth: true,  bucket: "E" },
  { id: "admin-support",                 role: "admin",     route: "/admin/support",                    requires_auth: true,  bucket: "E" },
  { id: "admin-support-ticket",          role: "admin",     route: "/admin/support-ticket",             requires_auth: true,  bucket: "E" },
  { id: "admin-blog",                    role: "admin",     route: "/admin/blog",                       requires_auth: true,  bucket: "E" },
  { id: "admin-blog-editor",             role: "admin",     route: "/admin/blog-editor",                requires_auth: true,  bucket: "E" },
  { id: "admin-blog-strategy",           role: "admin",     route: "/admin/blog-strategy",              requires_auth: true,  bucket: "E" },
  { id: "admin-blog-persona",            role: "admin",     route: "/admin/blog-persona",               requires_auth: true,  bucket: "E" },
];

export const VIEWPORTS = [
  { name: "desktop", width: 1440, height: 900,  deviceScaleFactor: 1, isMobile: false },
  { name: "mobile",  width: 390,  height: 844,  deviceScaleFactor: 2, isMobile: true,
    userAgent: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1" },
];

export function filterByBucket(bucket) {
  return PAGES.filter(p => p.bucket === bucket);
}

export function filterByRole(role) {
  return PAGES.filter(p => p.role === role);
}
